steps:
  publish:
    image: "eclipse-temurin:17-alpine"
    commands:
      - "./gradlew :API:publish -PkyngsRepoUsername=$${KYNGS_REPO_TOKEN} -PkyngsRepoPassword=$${KYNGS_REPO_SECRET}"
    when:
      - event: push
        branch:
          - master
          - dev
    secrets: [ kyngs_repo_token, kyngs_repo_secret ]